### PR TITLE
Updated Ml language resources and added more

### PR DESCRIPTION
**Pull request by ghost**
updated ml language resources and added more translations

### CODE REVIEW

**Comment by Sancus** [comment]
Thanks for the work.

I merged this manually, [please use Pontoon](https://pontoon.mozilla.org/projects/thunderbirdnet/) in the future as it's faster and less error prone for everyone involved.

**Comment by flodolo** [comment]
@Sancus 
Please only accept translations via Pontoon, not pull requests.

This PR just broke sync for this locale, and you have no visibility over that log.

**Comment by flodolo** [comment]
This, in particular
https://github.com/thundernest/thunderbird.net-l10n/commit/3f13903f67936930767cad4cfcdede143afdeeb7#diff-ae8f50b9938008ff04ef3aa7a0d31ebc3d6df09c2d29d9144711188b07e76fd9R513

**Comment by Sancus** [comment]
> This, in particular [3f13903#diff-ae8f50b9938008ff04ef3aa7a0d31ebc3d6df09c2d29d9144711188b07e76fd9R513](https://github.com/thundernest/thunderbird.net-l10n/commit/3f13903f67936930767cad4cfcdede143afdeeb7#diff-ae8f50b9938008ff04ef3aa7a0d31ebc3d6df09c2d29d9144711188b07e76fd9R513)

This is my fault, that shouldn't have been in there.

Committing changes works fine if you don't commit .po changes that don't parse, right? :P Fixed in https://github.com/thundernest/thunderbird.net-l10n/commit/ce3b4b3c49431797842e9925a063cd748daf4a75

**Comment by flodolo** [comment]
> Committing changes works fine if you don't commit .po changes that don't parse, right? :P

No, not really. 

The entire point of having a structured contribution path in Pontoon (manager, translators, contributors) is to ensure consistency and accountability. And changes made in GitHub will potentially overwritten changes made in Pontoon.

**Comment by Sancus** [comment]
> > Committing changes works fine if you don't commit .po changes that don't parse, right? :P
> 
> No, not really.
> 
> The entire point of having a structured contribution path in Pontoon (manager, translators, contributors) is to ensure consistency and accountability. And changes made in GitHub will potentially overwritten changes made in Pontoon.

The reason I asked is because the workflow to add/remove strings involves direct commits and it's always worked OK in the past.

I am happy to deny future requests to edit translations via PR, I don't like having to review them for problems that won't compile(which this one had) anyways.

**Comment by flodolo** [comment]
Commit to add strings to en-US (and merge the template to other locales) is OK, that's part of the expected workflow. Adding translation to the localized files is not.

P.S. not sure what's the process right now to add new strings, but if you're not doing it already, please disable the "fuzzy" option in `msgmerge`

**Pull request closed without merging**
